# Pipeline options in YAML format

hisat2:
    threads: 2
    memory_per_thread: 2G
    genome: data/hisat2_chr22
    options: --rna-strandness RF

picard:
    genome: data/Homo_sapiens.GRCh38.dna.chromosome.22.fa

feature_counts:
    gtf: data/chr22.genes2.gtf.gz
    options: -p -s 2
    threads: 2
